### PR TITLE
feat(plasma-ui): Add keys for `Pickers` components in stories

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.71.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  npm install @sberdevices/plasma-temple@1.53.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  npm install @sberdevices/plasma-ui@1.94.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  npm install @sberdevices/showcase@0.114.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  npm install @sberdevices/plasma-ui-docs@0.63.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.71.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  yarn add @sberdevices/plasma-temple@1.53.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  yarn add @sberdevices/plasma-ui@1.94.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  yarn add @sberdevices/showcase@0.114.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  yarn add @sberdevices/plasma-ui-docs@0.63.0-canary.1181.97ab37ed19d78de85eb6c6037f236f87d4261533.0
  ```
</details>

### CODE REVIEW

**Review by fanisco — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1181/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1181/
  ui storybook: http://plasma.sberdevices.ru/pr-1181/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1181/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1181/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1181/temple-storybook/

**Review by LamaEats — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1181/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1181/
  ui storybook: http://plasma.sberdevices.ru/pr-1181/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1181/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1181/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1181/temple-storybook/

**Pull request merged**
