### PR TITLE
fix(plasma-ui): fix simultaneous src&placeholder display

### PR DESCRIPTION
**Pull request by ayymkozb**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/showcase@0.18.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  npm install @sberdevices/plasma-icons@1.11.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  npm install @sberdevices/plasma-ui@1.14.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  npm install @sberdevices/plasma-web@1.12.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  # or 
  yarn add @sberdevices/showcase@0.18.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  yarn add @sberdevices/plasma-icons@1.11.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  yarn add @sberdevices/plasma-ui@1.14.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  yarn add @sberdevices/plasma-web@1.12.1-canary.390.881265e8ce9ea18778d05548637b92a4b4e1824b.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-390/
  http://plasma.sberdevices.ru/web-storybook-pr-390/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-390/
  http://plasma.sberdevices.ru/web-pr-390/

**Review by fanisco — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-390/
  http://plasma.sberdevices.ru/web-storybook-pr-390/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-390/
  http://plasma.sberdevices.ru/web-pr-390/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-390/
  http://plasma.sberdevices.ru/web-pr-390/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-390/
  http://plasma.sberdevices.ru/web-storybook-pr-390/

**Pull request merged**
