### PR TITLE
fix(plasma-web, plasma-b2c): Fix re-exporting

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.32.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-b2c@1.11.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-core@1.33.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-icons@1.47.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-ui@1.55.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-web@1.53.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-sb-utils@0.32.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/showcase@0.62.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-ui-docs@0.10.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  npm install @sberdevices/plasma-web-docs@0.6.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.32.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-b2c@1.11.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-core@1.33.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-icons@1.47.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-ui@1.55.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-web@1.53.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-sb-utils@0.32.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/showcase@0.62.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-ui-docs@0.10.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  yarn add @sberdevices/plasma-web-docs@0.6.2-canary.864.f7b7e1d72ccc747fe5520e61581ac0d4f56ba734.0
  ```
</details>

### CODE REVIEW

**Comment by fanisco** [comment]
`chore(**plamsa**-core)`
👍

**Comment by fanisco** [comment]
@neretin-trike все в один коммент слей, please

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-864/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-864/
  ui storybook: http://plasma.sberdevices.ru/pr-864/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-864/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-864/b2c-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-864/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-864/

**Pull request merged**
