### PR TITLE
fix(plasma-core): Add data selector for syntheticFocus in `addFocus` mixin

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.59.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-b2c@1.41.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-core@1.49.6-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-icons@1.67.7-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-temple@1.31.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-ui@1.82.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-web@1.76.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-sb-utils@0.48.6-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/showcase@0.97.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-ui-docs@0.43.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-web-docs@0.33.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  npm install @sberdevices/plasma-website@0.31.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.59.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-b2c@1.41.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-core@1.49.6-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-icons@1.67.7-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-temple@1.31.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-ui@1.82.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-web@1.76.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-sb-utils@0.48.6-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/showcase@0.97.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-ui-docs@0.43.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-web-docs@0.33.2-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  yarn add @sberdevices/plasma-website@0.31.1-canary.1113.eb62e28f202cb4ff6d0b2f0ee672934047bd4d82.0
  ```
</details>

### CODE REVIEW

**Review by fanisco — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1113/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1113/
  ui storybook: http://plasma.sberdevices.ru/pr-1113/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1113/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1113/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1113/temple-storybook/

**Review by kayman233 — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1113/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1113/
  ui storybook: http://plasma.sberdevices.ru/pr-1113/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1113/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1113/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1113/temple-storybook/

**Pull request merged**
