### PR TITLE
fix: Disabled state for `Checkbox` and `Radiobox`

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-docs@0.1.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  npm install @sberdevices/demo-canvas-app@0.23.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  npm install @sberdevices/plasma-icons@1.39.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  npm install @sberdevices/plasma-ui@1.46.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  npm install @sberdevices/plasma-web@1.44.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  npm install @sberdevices/plasma-sb-utils@0.24.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  npm install @sberdevices/showcase@0.51.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  # or 
  yarn add @sberdevices/plasma-docs@0.1.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  yarn add @sberdevices/demo-canvas-app@0.23.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  yarn add @sberdevices/plasma-icons@1.39.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  yarn add @sberdevices/plasma-ui@1.46.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  yarn add @sberdevices/plasma-web@1.44.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  yarn add @sberdevices/plasma-sb-utils@0.24.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  yarn add @sberdevices/showcase@0.51.3-canary.791.5cbd912667f09ae3819c685b21e62746d3f9a96d.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-791/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-791/
  ui storybook: http://plasma.sberdevices.ru/pr-791/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-791/web-storybook/

**Review by kayman233 — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-791/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-791/
  ui storybook: http://plasma.sberdevices.ru/pr-791/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-791/web-storybook/

**Pull request merged**
