### PR TITLE
fix: Pass `Image`'s width and height through args

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.38.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-b2c@1.17.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-core@1.35.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-icons@1.51.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-ui@1.61.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-web@1.57.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-sb-utils@0.34.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/showcase@0.70.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-ui-docs@0.17.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-web-docs@0.11.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  npm install @sberdevices/plasma-website@0.5.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.38.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-b2c@1.17.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-core@1.35.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-icons@1.51.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-ui@1.61.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-web@1.57.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-sb-utils@0.34.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/showcase@0.70.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-ui-docs@0.17.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-web-docs@0.11.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  yarn add @sberdevices/plasma-website@0.5.1-canary.909.d9ff10201c0ccd19285070f8176b1e37f83651c2.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-909/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-909/
  ui storybook: http://plasma.sberdevices.ru/pr-909/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-909/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-909/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-909/temple-storybook/

**Review by kayman233 — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-909/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-909/
  ui storybook: http://plasma.sberdevices.ru/pr-909/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-909/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-909/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-909/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-909/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-909/
  ui storybook: http://plasma.sberdevices.ru/pr-909/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-909/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-909/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-909/temple-storybook/

**Pull request merged**
