### PR TITLE
fix: Display `inline-flex` for `Badge`

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-docs@0.1.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/demo-canvas-app@0.23.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-core@1.27.3-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-icons@1.39.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-tokens-b2c@0.5.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-tokens-web@1.11.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-ui@1.46.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-web@1.44.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-sb-utils@0.24.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-tokens-android@2.19.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/plasma-tokens-ios-swift@2.19.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  npm install @sberdevices/showcase@0.51.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  # or 
  yarn add @sberdevices/plasma-docs@0.1.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/demo-canvas-app@0.23.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-core@1.27.3-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-icons@1.39.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-tokens-b2c@0.5.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-tokens-web@1.11.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-ui@1.46.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-web@1.44.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-sb-utils@0.24.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-tokens-android@2.19.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/plasma-tokens-ios-swift@2.19.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  yarn add @sberdevices/showcase@0.51.2-canary.784.cbfd11b2f0f940d01d90591d5abfb0ec8598a62a.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-784/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-784/
  ui storybook: http://plasma.sberdevices.ru/pr-784/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-784/web-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-784/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-784/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-784/
  ui storybook: http://plasma.sberdevices.ru/pr-784/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-784/web-storybook/

**Pull request merged**
