### PR TITLE
fix(plasma-ui): Toast fade top placement

### LINKED ISSUE #495: [Toast] При position: 'top' оверлэй все равно снизу
```
showToast('someText', 'top', undefined, true);
```

https://user-images.githubusercontent.com/33093997/124304812-ed5a4880-db6c-11eb-8398-9f0e35ccd5e2.mov

### PR DESCRIPTION
**Pull request by fanisco**
Closes #495 

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/showcase@0.31.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  npm install @sberdevices/demo-canvas-app@0.3.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  npm install @sberdevices/plasma-icons@1.23.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  npm install @sberdevices/plasma-ui@1.27.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  npm install @sberdevices/plasma-web@1.25.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  npm install @sberdevices/plasma-sb-utils@0.8.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  # or 
  yarn add @sberdevices/showcase@0.31.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  yarn add @sberdevices/demo-canvas-app@0.3.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  yarn add @sberdevices/plasma-icons@1.23.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  yarn add @sberdevices/plasma-ui@1.27.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  yarn add @sberdevices/plasma-web@1.25.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  yarn add @sberdevices/plasma-sb-utils@0.8.2-canary.528.90276fe6b24b303451dc601816d90e730b065d2b.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-528/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-528/
  http://plasma.sberdevices.ru/web-pr-528/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-528/
  http://plasma.sberdevices.ru/web-storybook-pr-528/

**Review by kvpolyanskiy — APPROVED** [review]

**Review by OgNellis — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-528/
  http://plasma.sberdevices.ru/web-pr-528/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-528/
  http://plasma.sberdevices.ru/web-storybook-pr-528/

**Pull request merged**
