### PR TITLE
fix(plama-web): Added possibility to specify a value type in `Select`

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-b2c@1.26.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  npm install @sberdevices/plasma-web@1.64.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  npm install @sberdevices/showcase@0.81.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  npm install @sberdevices/plasma-ui-docs@0.30.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  npm install @sberdevices/plasma-web-docs@0.21.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  npm install @sberdevices/plasma-website@0.15.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  # or 
  yarn add @sberdevices/plasma-b2c@1.26.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  yarn add @sberdevices/plasma-web@1.64.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  yarn add @sberdevices/showcase@0.81.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  yarn add @sberdevices/plasma-ui-docs@0.30.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  yarn add @sberdevices/plasma-web-docs@0.21.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  yarn add @sberdevices/plasma-website@0.15.1-canary.932.54c682715e524eb929a8d6a426f9542d4e8564b0.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-932/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-932/
  ui storybook: http://plasma.sberdevices.ru/pr-932/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-932/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-932/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-932/temple-storybook/

**Review by kayman233 — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-932/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-932/
  ui storybook: http://plasma.sberdevices.ru/pr-932/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-932/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-932/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-932/temple-storybook/

**Pull request merged**
