### PR TITLE
test(plasma-temple): Cart component tests

### PR DESCRIPTION
**Pull request by kvpolyanskiy**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-temple@1.35.0-canary.1067.6ad6b12e04706dd8da17365427e59f715e1264ec.0
  npm install @sberdevices/plasma-temple-docs@0.7.0-canary.1067.6ad6b12e04706dd8da17365427e59f715e1264ec.0
  # or 
  yarn add @sberdevices/plasma-temple@1.35.0-canary.1067.6ad6b12e04706dd8da17365427e59f715e1264ec.0
  yarn add @sberdevices/plasma-temple-docs@0.7.0-canary.1067.6ad6b12e04706dd8da17365427e59f715e1264ec.0
  ```
</details>

### CODE REVIEW

**Review by fanisco — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1067/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1067/
  ui storybook: http://plasma.sberdevices.ru/pr-1067/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1067/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1067/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1067/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1067/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1067/
  ui storybook: http://plasma.sberdevices.ru/pr-1067/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1067/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1067/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1067/temple-storybook/

**Pull request merged**
