### PR TITLE
feat(plasma-ui): A11y for `Toast`

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.38.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-b2c@1.17.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-core@1.35.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-icons@1.51.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-ui@1.61.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-web@1.57.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-sb-utils@0.34.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/showcase@0.70.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-ui-docs@0.17.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-web-docs@0.11.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  npm install @sberdevices/plasma-website@0.5.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.38.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-b2c@1.17.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-core@1.35.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-icons@1.51.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-ui@1.61.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-web@1.57.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-sb-utils@0.34.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/showcase@0.70.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-ui-docs@0.17.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-web-docs@0.11.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  yarn add @sberdevices/plasma-website@0.5.0-canary.710.993a8f2c5e6a22c3c6f1d927972e21d3100a21d7.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-710/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-710/
  ui storybook: http://plasma.sberdevices.ru/pr-710/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-710/web-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-710/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-710/
  ui storybook: http://plasma.sberdevices.ru/pr-710/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-710/web-storybook/

**Review by kayman233 — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-710/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-710/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-710/
  ui storybook: http://plasma.sberdevices.ru/pr-710/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-710/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-710/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-710/temple-storybook/

**Pull request merged**
