### PR TITLE
feat: `Dropdown` color, icon; fix: `Dropdown` radius, shadow

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.22.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  npm install @sberdevices/plasma-icons@1.39.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  npm install @sberdevices/plasma-ui@1.45.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  npm install @sberdevices/plasma-web@1.43.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  npm install @sberdevices/plasma-sb-utils@0.23.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  npm install @sberdevices/showcase@0.50.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.22.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  yarn add @sberdevices/plasma-icons@1.39.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  yarn add @sberdevices/plasma-ui@1.45.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  yarn add @sberdevices/plasma-web@1.43.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  yarn add @sberdevices/plasma-sb-utils@0.23.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  yarn add @sberdevices/showcase@0.50.0-canary.683.68e24f8cb7d88ec7f8445b0e7f70693e6fd07956.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-683/
  http://plasma.sberdevices.ru/web-pr-683/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-683/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-683/
  http://plasma.sberdevices.ru/web-storybook-pr-683/

**Review by LamaEats — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-683/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-683/
  http://plasma.sberdevices.ru/web-pr-683/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-683/
  http://plasma.sberdevices.ru/web-storybook-pr-683/

**Pull request merged**
