### PR TITLE
feat(plasma-web,plasma-b2c): Add focus for `Checkbox` and `Radiobox` components

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-b2c@1.50.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  npm install @sberdevices/plasma-web@1.85.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  npm install @sberdevices/showcase@0.106.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  npm install @sberdevices/plasma-ui-docs@0.55.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  npm install @sberdevices/plasma-web-docs@0.43.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  npm install @sberdevices/plasma-website@0.40.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  # or 
  yarn add @sberdevices/plasma-b2c@1.50.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  yarn add @sberdevices/plasma-web@1.85.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  yarn add @sberdevices/showcase@0.106.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  yarn add @sberdevices/plasma-ui-docs@0.55.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  yarn add @sberdevices/plasma-web-docs@0.43.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  yarn add @sberdevices/plasma-website@0.40.1-canary.1154.8bfaa727cff7c1fe2b1ec7be648f07f771917f83.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1154/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1154/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1154/
  ui storybook: http://plasma.sberdevices.ru/pr-1154/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1154/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1154/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1154/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1154/
  ui storybook: http://plasma.sberdevices.ru/pr-1154/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1154/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1154/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1154/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Pull request merged**
