### PR TITLE
fix: Separate `Input`'s animation by b2b and b2c

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.40.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-b2c@1.18.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-core@1.35.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-icons@1.51.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-ui@1.63.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-web@1.57.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-sb-utils@0.34.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/showcase@0.72.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-ui-docs@0.19.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-web-docs@0.11.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  npm install @sberdevices/plasma-website@0.6.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.40.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-b2c@1.18.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-core@1.35.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-icons@1.51.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-ui@1.63.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-web@1.57.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-sb-utils@0.34.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/showcase@0.72.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-ui-docs@0.19.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-web-docs@0.11.2-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  yarn add @sberdevices/plasma-website@0.6.1-canary.908.edee9289d5ff9b87cab19b020ce9414dcdeb17a4.0
  ```
</details>

### CODE REVIEW

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-908/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-908/
  ui storybook: http://plasma.sberdevices.ru/pr-908/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-908/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-908/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-908/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-908/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-908/
  ui storybook: http://plasma.sberdevices.ru/pr-908/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-908/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-908/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-908/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-908/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-908/
  ui storybook: http://plasma.sberdevices.ru/pr-908/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-908/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-908/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-908/temple-storybook/

**Pull request merged**
