### PR TITLE
fix(plasma-ui): `ActionButton`: Made `pin` not required again

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.54.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  npm install @sberdevices/plasma-temple@1.22.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  npm install @sberdevices/plasma-ui@1.77.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  npm install @sberdevices/showcase@0.91.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  npm install @sberdevices/plasma-ui-docs@0.38.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.54.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  yarn add @sberdevices/plasma-temple@1.22.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  yarn add @sberdevices/plasma-ui@1.77.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  yarn add @sberdevices/showcase@0.91.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  yarn add @sberdevices/plasma-ui-docs@0.38.1-canary.1045.d0577854b72aa4f189200dd348a61b81b5836e36.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1045/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1045/
  ui storybook: http://plasma.sberdevices.ru/pr-1045/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1045/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1045/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1045/temple-storybook/

**Review by LamaEats — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1045/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1045/
  ui storybook: http://plasma.sberdevices.ru/pr-1045/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1045/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1045/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1045/temple-storybook/

**Pull request merged**
