### PR TITLE
chore(plasma-temple): storybook ci

### PR DESCRIPTION
**Pull request by LamaEats**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-temple@1.3.0-canary.881.149003265710e1525cabaf96f13654b0b2538841.0
  npm install @sberdevices/plasma-website@0.4.0-canary.881.149003265710e1525cabaf96f13654b0b2538841.0
  # or 
  yarn add @sberdevices/plasma-temple@1.3.0-canary.881.149003265710e1525cabaf96f13654b0b2538841.0
  yarn add @sberdevices/plasma-website@0.4.0-canary.881.149003265710e1525cabaf96f13654b0b2538841.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-881/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-881/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-881/
  ui storybook: http://plasma.sberdevices.ru/pr-881/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-881/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-881/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-881/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-881/

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-881/
  ui storybook: http://plasma.sberdevices.ru/pr-881/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-881/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-881/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-881/temple-storybook/

**Pull request merged**
