### PR TITLE
feat(plasma-ui, plasma-core): Added `forwardedAs` and `as` props to `Tabs`

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-docs@0.0.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/demo-canvas-app@0.22.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/plasma-core@1.27.2-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/plasma-icons@1.39.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/plasma-ui@1.45.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/plasma-web@1.43.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/extract-sb-docgen-info@0.0.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/plasma-sb-utils@0.23.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  npm install @sberdevices/showcase@0.50.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  # or 
  yarn add @sberdevices/plasma-docs@0.0.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/demo-canvas-app@0.22.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/plasma-core@1.27.2-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/plasma-icons@1.39.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/plasma-ui@1.45.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/plasma-web@1.43.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/extract-sb-docgen-info@0.0.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/plasma-sb-utils@0.23.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  yarn add @sberdevices/showcase@0.50.1-canary.724.2482a64937b72da54ca6f748ce431153d4d5ab8f.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-724/

**Review by kayman233 — APPROVED** [review]

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-724/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-724/
  ui storybook: http://plasma.sberdevices.ru/pr-724/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-724/web-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-724/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-724/
  ui storybook: http://plasma.sberdevices.ru/pr-724/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-724/web-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-724/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-724/
  ui storybook: http://plasma.sberdevices.ru/pr-724/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-724/web-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-724/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  docs: http://plasma.sberdevices.ru/pr-724/
  ui storybook: http://plasma.sberdevices.ru/pr-724/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-724/web-storybook/

**Pull request merged**
