### PR TITLE
feat: `PaginationDots`: made `aria-hidden=true` by default

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.61.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-b2c@1.43.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-core@1.51.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-icons@1.69.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-temple@1.33.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-tokens-b2c@0.10.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-tokens-web@1.16.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-ui@1.84.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-web@1.78.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-cy-utils@0.7.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-sb-utils@0.50.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/showcase@0.99.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-ui-docs@0.45.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-web-docs@0.35.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  npm install @sberdevices/plasma-website@0.33.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.61.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-b2c@1.43.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-core@1.51.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-icons@1.69.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-temple@1.33.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-tokens-b2c@0.10.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-tokens-web@1.16.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-ui@1.84.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-web@1.78.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-cy-utils@0.7.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-sb-utils@0.50.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/showcase@0.99.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-ui-docs@0.45.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-web-docs@0.35.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  yarn add @sberdevices/plasma-website@0.33.0-canary.1108.60337f25483494318362a1c35f8ee116ca0fb566.0
  ```
</details>

### CODE REVIEW

**Review by kvpolyanskiy — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1108/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1108/
  ui storybook: http://plasma.sberdevices.ru/pr-1108/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1108/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1108/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1108/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1108/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1108/
  ui storybook: http://plasma.sberdevices.ru/pr-1108/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1108/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1108/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1108/temple-storybook/

**Pull request merged**
