### PR TITLE
feat: A11y Switch

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/showcase@0.45.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  npm install @sberdevices/demo-canvas-app@0.17.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  npm install @sberdevices/plasma-core@1.24.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  npm install @sberdevices/plasma-icons@1.34.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  npm install @sberdevices/plasma-ui@1.40.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  npm install @sberdevices/plasma-web@1.38.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  npm install @sberdevices/plasma-sb-utils@0.18.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  # or 
  yarn add @sberdevices/showcase@0.45.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  yarn add @sberdevices/demo-canvas-app@0.17.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  yarn add @sberdevices/plasma-core@1.24.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  yarn add @sberdevices/plasma-icons@1.34.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  yarn add @sberdevices/plasma-ui@1.40.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  yarn add @sberdevices/plasma-web@1.38.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  yarn add @sberdevices/plasma-sb-utils@0.18.0-canary.633.04a5152caf31b5e377d118cf30459e29ea53f078.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-633/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-633/
  http://plasma.sberdevices.ru/web-pr-633/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-633/
  http://plasma.sberdevices.ru/web-storybook-pr-633/

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-633/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-633/
  http://plasma.sberdevices.ru/web-pr-633/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-633/
  http://plasma.sberdevices.ru/web-storybook-pr-633/

**Pull request merged**
