### PR TITLE
fix(plasma-ui): `HeaderArrow`: made unfocusable

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.58.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-b2c@1.39.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-core@1.49.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-icons@1.67.5-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-temple@1.29.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-tokens-b2c@0.8.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-tokens-web@1.14.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-tokens@1.15.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-ui@1.81.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-web@1.75.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-cy-utils@0.5.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-sb-utils@0.48.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-tokens-android@2.22.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-tokens-ios-swift@2.22.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-tokens-utils@0.9.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/showcase@0.95.6-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-temple-docs@0.5.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-ui-docs@0.42.6-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-web-docs@0.32.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  npm install @sberdevices/plasma-website@0.29.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.58.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-b2c@1.39.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-core@1.49.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-icons@1.67.5-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-temple@1.29.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-tokens-b2c@0.8.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-tokens-web@1.14.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-tokens@1.15.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-ui@1.81.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-web@1.75.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-cy-utils@0.5.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-sb-utils@0.48.4-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-tokens-android@2.22.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-tokens-ios-swift@2.22.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-tokens-utils@0.9.1-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/showcase@0.95.6-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-temple-docs@0.5.2-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-ui-docs@0.42.6-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-web-docs@0.32.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  yarn add @sberdevices/plasma-website@0.29.7-canary.1076.f6f9000b5272fb033ab3716b0f1fa25771df39dc.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1076/

**Review by didolf — APPROVED** [review]

**Review by neretin-trike — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1076/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1076/
  ui storybook: http://plasma.sberdevices.ru/pr-1076/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1076/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1076/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1076/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1076/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1076/
  ui storybook: http://plasma.sberdevices.ru/pr-1076/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1076/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1076/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1076/temple-storybook/

**Pull request merged**
