### PR TITLE
feat(demo-canvas-app): Added Switch to PickersPage

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/showcase@0.33.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  npm install @sberdevices/demo-canvas-app@0.5.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  npm install @sberdevices/plasma-icons@1.25.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  npm install @sberdevices/plasma-ui@1.29.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  npm install @sberdevices/plasma-web@1.27.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  npm install @sberdevices/plasma-sb-utils@0.10.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  # or 
  yarn add @sberdevices/showcase@0.33.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  yarn add @sberdevices/demo-canvas-app@0.5.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  yarn add @sberdevices/plasma-icons@1.25.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  yarn add @sberdevices/plasma-ui@1.29.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  yarn add @sberdevices/plasma-web@1.27.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  yarn add @sberdevices/plasma-sb-utils@0.10.0-canary.542.e86662d3c5ab7e114b7f4756ae56e4dec468ee24.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-542/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-542/
  http://plasma.sberdevices.ru/web-pr-542/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-542/
  http://plasma.sberdevices.ru/web-storybook-pr-542/

**Review by kvpolyanskiy — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-542/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-542/
  http://plasma.sberdevices.ru/web-storybook-pr-542/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-542/
  http://plasma.sberdevices.ru/web-pr-542/

**Pull request merged**
