### PR TITLE
feat(plasma-icons): Remove `IconVolumeMute` and mark `IconSpinner` as deprecated 

### PR DESCRIPTION
**Pull request by neretin-trike**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.43.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-b2c@1.21.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-icons@1.54.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-ui@1.66.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-web@1.60.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/showcase@0.75.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-ui-docs@0.25.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-web-docs@0.17.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  npm install @sberdevices/plasma-website@0.10.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.43.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-b2c@1.21.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-icons@1.54.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-ui@1.66.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-web@1.60.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/showcase@0.75.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-ui-docs@0.25.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-web-docs@0.17.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  yarn add @sberdevices/plasma-website@0.10.0-canary.919.963ad92621e1a89f57cd1536ee8b43bf55f3051b.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-919/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-919/
  ui storybook: http://plasma.sberdevices.ru/pr-919/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-919/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-919/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-919/temple-storybook/

**Review by kayman233 — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-919/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-919/
  ui storybook: http://plasma.sberdevices.ru/pr-919/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-919/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-919/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-919/temple-storybook/

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-919/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-919/
  ui storybook: http://plasma.sberdevices.ru/pr-919/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-919/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-919/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-919/temple-storybook/

**Pull request merged**
