### PR TITLE
docs(plasma-ui): assistant usage fix

### PR DESCRIPTION
**Pull request by kayman233**

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-562/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-562/
  http://plasma.sberdevices.ru/web-storybook-pr-562/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-562/
  http://plasma.sberdevices.ru/web-pr-562/

**Review by fanisco — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-562/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  http://plasma.sberdevices.ru/pr-562/
  http://plasma.sberdevices.ru/web-pr-562/

**Comment by SberDevices-Eva** [comment]
Storybook preview deployed!
  
  http://plasma.sberdevices.ru/ui-storybook-pr-562/
  http://plasma.sberdevices.ru/web-storybook-pr-562/

**Pull request merged**
