### PR TITLE
revert: #948 and #979

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/plasma-temple-docs@0.3.1-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  npm install @sberdevices/plasma-ui-docs@0.31.2-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  npm install @sberdevices/plasma-web-docs@0.22.2-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  npm install @sberdevices/plasma-website@0.16.3-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  # or 
  yarn add @sberdevices/plasma-temple-docs@0.3.1-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  yarn add @sberdevices/plasma-ui-docs@0.31.2-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  yarn add @sberdevices/plasma-web-docs@0.22.2-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  yarn add @sberdevices/plasma-website@0.16.3-canary.982.880986bb87201c2b48809c700e12973e6fff961f.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-982/

**Review by neretin-trike — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-982/
  ui storybook: http://plasma.sberdevices.ru/pr-982/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-982/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-982/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-982/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-982/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-982/
  ui storybook: http://plasma.sberdevices.ru/pr-982/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-982/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-982/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-982/temple-storybook/

**Pull request merged**
