### PR TITLE
fix(plasma-web): `Carousel`: moved style resets to core

### PR DESCRIPTION
**Pull request by fanisco**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @sberdevices/demo-canvas-app@0.59.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-b2c@1.41.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-core@1.49.6-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-icons@1.67.7-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-temple@1.31.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-ui@1.82.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-web@1.76.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-sb-utils@0.48.6-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/showcase@0.97.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-ui-docs@0.43.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-web-docs@0.33.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  npm install @sberdevices/plasma-website@0.31.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  # or 
  yarn add @sberdevices/demo-canvas-app@0.59.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-b2c@1.41.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-core@1.49.6-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-icons@1.67.7-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-temple@1.31.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-ui@1.82.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-web@1.76.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-sb-utils@0.48.6-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/showcase@0.97.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-ui-docs@0.43.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-web-docs@0.33.2-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  yarn add @sberdevices/plasma-website@0.31.1-canary.1104.7afcb82860cc1a4d585a889146622c9d4920684c.0
  ```
</details>

### CODE REVIEW

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1104/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1104/
  ui storybook: http://plasma.sberdevices.ru/pr-1104/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1104/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1104/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1104/temple-storybook/

**Review by Yeti-or — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]

**Comment by SberDevices-Eva** [comment]
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-1104/

**Comment by SberDevices-Eva** [comment]
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-1104/
  ui storybook: http://plasma.sberdevices.ru/pr-1104/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-1104/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-1104/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-1104/temple-storybook/

**Pull request merged**
